language: elixir
elixir:
- 1.3.4
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database mmserver_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: baZd7f87DeSx4QSgjWMvmL0J/fAApo22GQCOwwDwolYO7kNTKry9x1XGSvZddWPGOBfD3a/iIOa+spXSzInrE8LweLxXNe3LCpLzglCMzf+GUGg4/MTbsmdQ8Xy3dmqiJK94XrkfSYG0MsrUtsOlftwwb9FTEgdienDvrfdzi/o/KwnHOk2F/sv+iWvQ4R/9p6p05XNe3r/RJiNeubzYETzScA+ja/viHOCzh1/jrg6m1v7g2lk60dcg0qzhUG/q7V4+LaKymIJB60iXLTb3RSKDunUy+fb5A3LRiXtyRtOzMSXvX63gqoPTBh+A4LzRWn6cZukAPQkScY1W2nw3+qoKe/B2eJEMym1h7Jji9xc++90uaA4PuzQWvlxnB6i/XXEo3v5q1NAUTycpWR83uqBw6KVoItnLdg15kZ+pgZ99XFzyLzHwH1hY3yaANCDea09PP2MWBhYpayz0knJ+oiT91T+XodudcF1O62cYEFT9DmbJjm0eLMURQ6bezgC/wPffAUsv9DJS3efWnaG/TJmot+Lk71Rx04LARu4b6XI5V5ojvNA+3ELT2y8ogkemqx4WhlD1hkJak29vwfpIZcJW4SmQecdC8Qji2HC93INLlIHsviz4gyFV6Qz+0SMJU0U/KNWf69OxCrC/PysPQmB6faYFPlbuOoWNhp7jieM=
  app: ek-mm-server
  on:
    repo: elanalynn/mentor_match_server
